name: Flake Update

on:
  workflow_dispatch:
  schedule: #once a week
    - cron:  '0 0 * * 0'

jobs:
  flake-update:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Nix
      uses: cachix/install-nix-action@v23
      with: 
        nix_path: nixpkgs=channel:nixos-unstable

    - name: Update flake
      run: nix flake update

    - name: Check flake updates
      run: nix flake check

    - name: Commit
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "Update flake"

