name: Nix Linting

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Nix
        # You may pin to the exact commit or the version.
        # uses: cachix/install-nix-action@6a9a9e84a173d90b3ffb42c5ddaf9ea033fad011
      uses: cachix/install-nix-action@v23
        
    - name: List Nix Packages
      run: nix-env -q
      
    - name: Print PATH
      run: echo $PATH
    
    - name: Setup Cachix
      uses: cachix/cachix-action@v23
      with:
        name: nix-linter

    - name: Clone nix-linter and run checks
      run: |
        git clone https://github.com/Synthetica9/nix-linter
        cd nix-linter
        linter_path=$(nix-build -A nix-linter)
        $linter_path/bin/nix-linter ./*.nix  # Adjust path as per your requirement
