name: Nix Linting

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Cachix
      uses: cachix/cachix-action@v10
      with:
        name: nix-linter
       
    - name: Clone nix-linter and run checks
      run: |
        git clone https://github.com/Synthetica9/nix-linter
        cd nix-linter
        linter_path=$(nix-build -A nix-linter)
        $linter_path/bin/nix-linter ./*.nix  # Adjust path as per your requirement
