name: Nix Linting

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Nix
      uses: cachix/install-nix-action@v14

    - name: Install nix-linter
      run: nix-env -iA nix-linter

    - name: Run nix-linter
      run: nix-linter ./*.nix  # Adjust the path as per your repository structure

